services:
  tesseract-engine:
    image: maduraitamilan/tesseract-engine:v1.0.0
  springboot-tesseract-master:
    image: maduraitamilan/tesseract-master:v1.0.0          
    ports:
      - "8443:8443"
    environment: 
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
    depends_on:
      - tesseract-engine
