version: '3.1'

services:

  tess4j-ocr:
    container_name: ocr-tesseract
    image: maduraitamilan/ocr-tesseract
    restart: always  
    ports:
      - "8445:8445"
    environment:
      - LC_ALL=C
      - TESSDATA_PREFIX=/usr/share/tessdata
