services:
  springboot-tesseract-master:
    image: maduraitamilan/tesseract-master:v1.0.0          
    ports:
      - "8443:8443"
    environment:
      - LC_ALL=C
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
